"""Coordinate the existing Gemini adapter's cache across episode workers.

The adapter and its input fingerprint stay unchanged, so existing audio runs can
still resume. Shared cache entries must never be regenerated by two workers.
"""
from .speech import GeminiSpeech, speech_settings
from .spoken_forms import SpokenForms, spoken_text
from .storage import digest, file_hash, file_lock, write_json


class LockedGeminiSpeech(GeminiSpeech):
    def synthesize(self, text, voice, language, cache, spoken=None):
        key = digest(speech_settings(text, voice, language, spoken, self.model))
        with file_lock(cache / "locks" / (key + ".lock"), timeout=self.timeout + 30):
            # Recursive splits use this method as well. Each child is shorter,
            # so lock dependencies cannot form a cycle.
            return super().synthesize(text, voice, language, cache, spoken)


def run_parallel_gemini_tts(config, script, root, work, choice, api_key=None, *, table=None, overrides=None):
    engine = LockedGeminiSpeech(api_key, timeout=config.runtime.tts_timeout_seconds, model=choice.model)
    table = table if table is not None else SpokenForms()
    rows, paths = [], []
    for segment in script.segments:
        write_json(work / "tts_progress.json", {"completed_segments": len(rows),
            "total_segments": len(script.segments), "current_segment": segment.segment_id})
        voice = choice.voices[segment.speaker_id]
        spoken = spoken_text(segment, table, overrides)
        path = engine.synthesize(segment.text, voice, config.language, root / "cache/audio/gemini", spoken=spoken)
        paths.append(path)
        rows.append({"segment_id": segment.segment_id, "path": path.relative_to(root / "cache/audio").as_posix(),
            "sha256": file_hash(path), "settings": speech_settings(segment.text, voice, config.language, spoken, choice.model)})
    write_json(work / "tts_report.json", {"segments": rows})
    write_json(work / "tts_progress.json", {"completed_segments": len(rows), "total_segments": len(rows)})
    return paths
