"""Coordinate the existing Gemini adapter's cache across episode workers.

The adapter and its input fingerprint stay unchanged, so existing audio runs can
still resume. Shared cache entries must never be regenerated by two workers.
"""
import os

from .speech import GeminiSpeech, run_gemini_tts, shared_throttle, speech_settings
from .storage import digest, file_lock


def release_lock_file(path):
    """Delete a segment's lock file once nobody holds or waits for it (2026-10-02: 830 and 551 were left in two
    projects). Windows refuses to delete a file another worker has open, and a waiting worker keeps its lock file
    open, so the deletion fails exactly when it would be unsafe. Elsewhere a deleted lock file could be held twice
    (one worker on the old file, one on a new one), so it stays."""
    if os.name != "nt":
        return
    try:
        path.unlink(missing_ok=True)
    except OSError:
        pass


def release_lock_files(cache):
    """Clear the lock files earlier recordings left behind; one that is held or awaited stays."""
    folder = cache / "locks"
    if os.name == "nt" and folder.is_dir():
        for path in folder.glob("*.lock"):
            release_lock_file(path)


class LockedGeminiSpeech(GeminiSpeech):
    def synthesize(self, text, voice, language, cache, spoken=None):
        key = digest(speech_settings(text, voice, language, spoken, self.model))
        lock = cache / "locks" / (key + ".lock")
        try:
            with file_lock(lock, timeout=self.timeout + 30):
                # Recursive splits use this method as well. Each child is shorter,
                # so lock dependencies cannot form a cycle.
                return super().synthesize(text, voice, language, cache, spoken)
        finally:
            release_lock_file(lock)


def run_parallel_gemini_tts(config, script, root, work, choice, api_key=None, *, table=None, overrides=None,
                            expression=None):
    """``speech.run_gemini_tts`` with the shared cache locked per segment."""
    release_lock_files(root / "cache/audio/gemini")
    engine = LockedGeminiSpeech(api_key, timeout=config.runtime.tts_timeout_seconds, model=choice.model,
                                throttle_file=shared_throttle(root))
    return run_gemini_tts(config, script, root, work, choice, api_key, table=table, overrides=overrides,
                          expression=expression, engine=engine)
